name: Publish to PyPI (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to publish (e.g., v1.0.0)"
        required: true

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Download distribution artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ github.event.inputs.tag }}
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
